### PR TITLE
CEP-189: Dag archive upload

### PR DESCRIPTION
**Pull request by a-bek**
This PR adds a new api endpoint `deploy_dag_archive`

Parameters
1) Upload an archive
2) Options to:
     - delete current dags in airflow
     - force update over existing dag

### CODE REVIEW

**Comment by ixalon** [comment]
I'm not sure such a large change is required. Airflow handles ZIP files in the DAG directory natively: https://airflow.apache.org/concepts.html?highlight=zip#packaged-dags

The single-file upload endpoint can be used, but it must be changed to accept either .py files or .zip files (this is a very small change).

**Comment by a-bek** [comment]
Yes, however, Airflow's handling of ZIP files is slightly restricted. It strictly handles zipped files and not directories so we would have to package all files in one directory level. Ideally, we'd like our dag directory to look something like:

```
dags/
dags/neustar/
dags/neustar/common/
dags/adform/
dags/adform/common/
```
This makes our code cleaner.

This change allows a bit more flexibility of loading dags using zip, and is more explicit as the current endpoint handles only '.py' files and has no documentation on the zipped file structure required for internal Airflow unpackaging.

However, I do see that extending the logic of unpacking the zips should ideally be baked into the airflow core rather than in the plugin, which would require contributing directly to Airflow source rather than here. (This would require contributing to Airflow, which will take time to propagate)

So we have two options, moving ahead with one of two solutions that currently work:
1) Cancel this change, adopt a single level, flat dag structure that stores all the files required. (works)
2) Deploy this change (works)

**Comment by ixalon** [comment]
Looking at the airflow code it looks as if it will find ZIP files within subdirectories of the DAG folder: https://github.com/apache/airflow/blob/717ddaf737ec1c57244377f73dd0e80e1628576a/airflow/utils/dag_processing.py#L279-L280

The comment on https://airflow.apache.org/concepts.html?highlight=zip#packaged-dags regarding subfolders is that **within** each zip file, it will only scan .py files for DAGs within the root of the zip.

This means the FS would be something like:
```
dags/
dags/neustar/neustar-dags.zip
dags/adform/adform-dags.zip
```

Within neustar-dags.zip you could have:
```
dag1.py
dag2.py
common/__init__.py
common/functions.py
common/utils.py
otherlib/__init__.py
otherlib/something.py
...
```

I just worry that if we are going to use ZIPs and start using them in a way that's different from Airflow's documented functionality, we're going to hit problems and confusion later down the line.

**Comment by a-bek** [comment]
Unfortunately, we won't be able to deploy non-dag modules using this endpoint, because the unzipped files are not actually saved, the dags are just imported at runtime and added to the dagbag (They won't be able to reference any of the non-dag modules added). I'm going to do a bit more digging to see if there would be any pitfalls with the solution I have provided.

**Comment by ixalon** [comment]
I might be misunderstanding but the whole purpose of Airflow packaged DAGs (https://airflow.apache.org/concepts.html?highlight=zip#packaged-dags) is that all the DAG's dependencies can be packaged up into the DAG zip file and deployed in one file.

Can you explain how this does this not meet your requirements?

It's far better to use the conventional approach if we can.

**Comment by a-bek** [comment]
Yes, you can deploy airflow DAGs with a zip in the DAG directory when deploying Airflow itself, but the current plugin endpoint has strange behaviour when I deploy a zip while Airflow is running. For example, DAGs keep disappearing and reappearing in the interface.

The new endpoint, for deploying zips while Airflow is running, works fine, as far as I'm aware, having manually tested both several times using different Airflow states.

**Comment by ixalon** [comment]
Ok, if we must avoid Airflow’s packaged dags support we should at least make this new endpoint take a mandatory top-level folder name and unzip all the files into the specified folder within the dags directory.

Otherwise there is a good chance people will create zips which inadvertently overwrite something deployed as part of another DAG archive.

**Pull request merged**
